name: Deploy NYC Mesh Calendar Bot

on:
  workflow_run:
    workflows: ["Publish Docker Image"]
    types:
      - completed

jobs:
  deploy_nyc_mesh_calendar_bot:
    runs-on: ubuntu-latest
    steps:
      - name: Install SSH key
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.ANDY_BOX_KEY }}
          name: id_ed25519 # optional
          known_hosts: ${{ secrets.ANDY_KNOWN_HOSTS }}
          #config: ${{ secrets.CONFIG }} # ssh_config; optional
          if_key_exists: fail # replace / ignore / fail; optional (defaults to fail)
      - name: Pull new Docker image
        run: ssh ubuntu@status.mesh.nycmesh.net "cd /home/ubuntu/nycmesh-calendar-bot && bash update_and_restart.sh"
